---
title: "Basic Regressions"
author: "Tom"
date: "September 21, 2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

#options(width = 300)

# packages 
library(tidyverse)
library(readstata13)
library(shiny)

# object with outcome variables 
yvars <- c("student_knowledge",
           "ecd_student_knowledge",
           "inputs",
           "infrastructure",
           "intrinsic_motivation",
            "content_knowledge",
           "operational_manage",
           "instr_leader",
           "principal_knowl_score",
           "principal_manage",
           "bi",
           "national_learning_goals",
           "mandates_accountability",
           "quality_bureaucracy",
           "impartial_decision_making")

#load data 
md <- read.dta13(file = "C:/Users/WB551206/OneDrive - WBG/Documents/Dashboard/global-education-dashboard/baseline/DataSets/final/merge_district_tdist.dta",
                 convert.factors = TRUE) 


# create new dataset: missing values 



```





## Interactive By-Country Visualizations
Select up to two pairs of explanatory variables (Bureaucracy Indicators) and Outcomes Variables (School Outcomes) to visualize the scatterplots and best-fit lines by country.

###Variable Selector
Plot 1
```{r}


# inputs 1
selectInput("yvar1", #inputid
            "Outcome Variable 1", #label
           choices = c("Student Knowledge" = "student_knowledge",
           "1st Grade Student Knowledge" = "ecd_student_knowledge",
           "Inputs" = "inputs",
           "Infrastructure" = "infrastructure",
           "Teacher Motivation" = "intrinsic_motivation",
           "Teacher Content Knowledge" = "content_knowledge",
           "Operational Management" = "operational_manage",
           "Instructional Leadership" = "instr_leadership",
           "Principal Knolwedge Score" = "principal_knowl_score",
           "Principal Management" = "principal_manage"),
           multiple = FALSE,
           selected = "infrastructure"
)
           
selectInput("xvar1", #inputid
            "Explanatory Variable 1", #label
           choices = c("Bureaucracy Index" = "bi",
                       "National Learning Goals" = "national_learning_goals",
                       "Mandates and Accountability" = "mandates_accountability",
                       "Quality of Bureaucracy" = "quality_bureaucracy",
                       "Impartial Decision-Making" = "impartial_decision_making"),
           multiple = FALSE,
           selected = "bi"
)
```



Plot 2
```{r}
# inputs 2
selectInput("yvar2", #inputid
            "Outcome Variable 2", #label
           choices = c("Student Knowledge" = "student_knowledge",
           "1st Grade Student Knowledge" = "ecd_student_knowledge",
           "Inputs" = "inputs",
           "Infrastructure" = "infrastructure",
           "Teacher Motivation" = "intrinsic_motivation",
           "Teacher Content Knowledge" = "content_knowledge",
           "Operational Management" = "operational_manage",
           "Instructional Leadership" = "instr_leadership",
           "Principal Knolwedge Score" = "principal_knowl_score",
           "Principal Management" = "principal_manage"),
           multiple = FALSE,
           selected = "content_knowledge"
)
           
selectInput("xvar2", #inputid
            "Explanatory Variable 2", #label
           choices = c("Bureaucracy Index" = "bi",
                       "National Learning Goals" = "national_learning_goals",
                       "Mandates and Accountability" = "mandates_accountability",
                       "Quality of Bureaucracy" = "quality_bureaucracy",
                       "Impartial Decision-Making" = "impartial_decision_making"),
           multiple = FALSE,
           selected = "national_learning_goals"
)



```


Plot 1
```{r, fig.align='center', fig.show='hold'}

# plot 1
renderPlot({
  # make the plot 
 ggplot(md, aes_string(input$xvar1, input$yvar1)) +
    geom_jitter() +
    geom_smooth(method = lm) +
    facet_wrap(~ countryname)
  
},
# plot options
  width  = 500,
  height = 400,
  res = 100
)


```

Plot 2

```{r}



# plot 2         
renderPlot({
  # make the plot 
 ggplot(md, aes_string(input$xvar2, input$yvar2)) +
    geom_jitter() +
    geom_smooth(method = lm) +
    facet_wrap(~ countryname)
  
},
# plot options
  width  = 500,
  height = 400,
  res = 100
)



```
 